[package]
name = "Junioraufgabe2"
version = "0.1.0"
edition = "2021"

[dependencies]

# Special config for the binary because src dir is called Quelltext and not src
[[bin]]
name = "hopser"
path = "Quelltext/main.rs"